# Generated by Django 5.2.12 on 2026-04-05 11:15

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Xpertpharm'), (0, 'Interne')], default=1)),
                ('query', models.TextField()),
                ('parameters', models.JSONField()),
                ('help', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('min_duration', models.DurationField(blank=True, default=datetime.timedelta, null=True)),
                ('shift_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('duration', models.DurationField(default=datetime.timedelta)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='XpertServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('servername', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('driver', models.CharField(choices=[('ODBC Driver 17 for SQL Server', 'ODBC Driver 17 for SQL Server'), ('ODBC Driver 18 for SQL Server', 'ODBC Driver 18 for SQL Server'), ('FreeTDS', 'FreeTDS'), ('SQL Server', 'SQL Server')], default='FreeTDS', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default=None, max_length=100)),
                ('number_of_packs', models.PositiveIntegerField()),
                ('cold_chain', models.BooleanField(blank=True, default=None, null=True)),
                ('psycho', models.BooleanField(blank=True, default=None, null=True)),
                ('correct_destination', models.BooleanField(blank=True, default=None, null=True)),
                ('products_type', models.BooleanField(blank=True, default=None, null=True)),
                ('ref_tiers', models.CharField(default=None, max_length=50, null=True)),
                ('reception_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saisie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_tiers', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_lines', models.PositiveIntegerField()),
                ('employee1_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee1_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee2_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee2_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee3_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee3_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_employee1', to='accounts.employee')),
                ('employee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_employee2', to='accounts.employee')),
                ('employee3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_employee3', to='accounts.employee')),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.reception')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_tiers', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_lines', models.PositiveIntegerField()),
                ('employee1_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee1_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee2_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee2_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee3_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee3_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_employee1', to='accounts.employee')),
                ('employee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_employee2', to='accounts.employee')),
                ('employee3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_employee3', to='accounts.employee')),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.saisie')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_salary', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('G', 'Gain'), ('R', 'Retenue')], max_length=1)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Another Item'), ('addition', 'Addition of Another Item'), ('deduction', 'Deduction from Another Item'), ('product', 'Product with Another Item'), ('division', 'Division by Another Item'), ('formula', 'Custom Formula'), ('multiply_days', 'Multiply by Number of Days'), ('multiply_hours', 'Multiply by Number of Hours')], default='fixed', max_length=20)),
                ('default_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dependent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ounissi_app.salaryitem')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.salary')),
                ('salary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.salaryitem')),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_items',
            field=models.ManyToManyField(through='ounissi_app.SalaryDetail', to='ounissi_app.salaryitem'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('schedule_status', models.IntegerField(choices=[(0, 'Planifié'), (1, 'En Cours'), (2, 'Non Clôturé'), (3, 'Clôturé')], default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'start_time', 'end_time'), name='unique_schedule_datetime')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours', models.DurationField(blank=True, default=datetime.timedelta, null=True)),
                ('total_assigned_time', models.DurationField(blank=True, default=datetime.timedelta, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_time', models.DurationField(default=datetime.timedelta)),
                ('progression_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('progress_lines', models.IntegerField(blank=True, default=0, null=True)),
                ('task_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='saisie',
            name='employee1_schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_details_1', to='ounissi_app.scheduleitem'),
        ),
        migrations.AddField(
            model_name='saisie',
            name='employee2_schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_details_2', to='ounissi_app.scheduleitem'),
        ),
        migrations.AddField(
            model_name='saisie',
            name='employee3_schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_details_3', to='ounissi_app.scheduleitem'),
        ),
        migrations.CreateModel(
            name='ReceptionVignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_tiers', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_lines', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee1_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee1_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee2_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee2_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee3_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee3_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vignette_employee1', to='accounts.employee')),
                ('employee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vignette_employee2', to='accounts.employee')),
                ('employee3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vignette_employee3', to='accounts.employee')),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.receptionproduit')),
                ('employee1_schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_vignette_1', to='ounissi_app.scheduleitem')),
                ('employee2_schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_vignette_2', to='ounissi_app.scheduleitem')),
                ('employee3_schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_vignette_3', to='ounissi_app.scheduleitem')),
            ],
        ),
        migrations.AddField(
            model_name='receptionproduit',
            name='employee1_schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_verification_1', to='ounissi_app.scheduleitem'),
        ),
        migrations.AddField(
            model_name='receptionproduit',
            name='employee2_schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_verification_2', to='ounissi_app.scheduleitem'),
        ),
        migrations.AddField(
            model_name='receptionproduit',
            name='employee3_schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_verification_3', to='ounissi_app.scheduleitem'),
        ),
        migrations.CreateModel(
            name='ReceptionPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_tiers', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_lines', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee1_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee1_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee2_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee2_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee3_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('employee3_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('employee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Placement_employee1', to='accounts.employee')),
                ('employee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Placement_employee2', to='accounts.employee')),
                ('employee3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Placement_employee3', to='accounts.employee')),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.receptionvignette')),
                ('employee1_schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_Placement_1', to='ounissi_app.scheduleitem')),
                ('employee2_schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_Placement_2', to='ounissi_app.scheduleitem')),
                ('employee3_schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_Placement_3', to='ounissi_app.scheduleitem')),
            ],
        ),
        migrations.AddField(
            model_name='reception',
            name='related_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_details', to='ounissi_app.scheduleitem'),
        ),
        migrations.CreateModel(
            name='AssignationEmplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(blank=True, max_length=10, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ounissi_app.stockoperation')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(blank=True, max_length=200, null=True)),
                ('average_duration', models.DurationField(blank=True, default=datetime.timedelta, null=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Priorite 1'), (2, 'Priorite 2'), (3, 'Priorite 3'), (4, 'Priorite 4')], default=4)),
                ('repeat_freq', models.PositiveIntegerField(blank=True, null=True)),
                ('menu', models.BooleanField(default=False)),
                ('transfer', models.BooleanField(default=False)),
                ('progress_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ounissi_app.query')),
                ('responsibility_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rank')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.tasktype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ounissi_app.task'),
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.DurationField(blank=True, default=datetime.timedelta, null=True)),
                ('completion', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed'), (3, 'Overdue'), (4, 'Reported')], default=0)),
                ('total_assigned_time', models.DurationField(blank=True, default=datetime.timedelta, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.schedule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.task')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ounissi_app.task'),
        ),
        migrations.CreateModel(
            name='TaskGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('generated_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggering_task', to='ounissi_app.task')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_tasks', to='ounissi_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, default=None)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('start_time_2', models.TimeField(blank=True, default=None, null=True)),
                ('end_time_2', models.TimeField(blank=True, default=None, null=True)),
                ('start_time_3', models.TimeField(blank=True, default=None, null=True)),
                ('end_time_3', models.TimeField(blank=True, default=None, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='unique_employee_month'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date'),
        ),
    ]
