# Generated by Django 5.2.12 on 2026-04-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_xp_id_alter_employee_zk_id'),
        ('ounissi_app', '0003_usersynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(db_index=True, max_length=100)),
                ('ref_tiers', models.CharField(db_index=True, max_length=50)),
                ('reception_date', models.DateField(auto_now_add=True, db_index=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v3_process', to='ounissi_app.reception')),
            ],
            options={
                'verbose_name': 'Workflow de Réception',
                'ordering': ['-reception_date'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_step', models.CharField(choices=[('REC', 'Réception'), ('SAI', 'Saisie'), ('PRO', 'Produit'), ('VIG', 'Vignette'), ('PLA', 'Placement')], db_index=True, max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Assigné'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé')], default='PENDING', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('task_data', models.JSONField(blank=True, default=dict)),
                ('employees', models.ManyToManyField(blank=True, related_name='assigned_reception_tasks', to='accounts.employee')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ounissi_app.receptionprocess')),
            ],
            options={
                'verbose_name': 'Tâche de Réception',
                'unique_together': {('process', 'task_step')},
            },
        ),
    ]
