# Generated by Django 5.2.12 on 2026-07-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ounissi_app', '0004_receptionprocess_receptiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='leave_type',
            field=models.CharField(choices=[('NONE', 'Aucun'), ('PAID', 'Congé Payé'), ('SICK', 'Congé Maladie'), ('UNPAID', 'Congé Sans Solde'), ('OTHER', 'Autre')], default='NONE', max_length=10, verbose_name='Type de Congé'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
