# Generated by Django 5.2.12 on 2026-04-05 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ounissi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_items',
            field=models.ManyToManyField(blank=True, to='ounissi_app.salaryitem'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rank'),
        ),
        migrations.AddField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(related_name='teams', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee'),
        ),
    ]
