# Generated by Django 5.2.12 on 2026-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='xp_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zk_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
