# Generated by Django 5.2.12 on 2026-08-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_xp_id_alter_employee_zk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_accrual_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Nombre de jours de congé accumulés par mois valide (ex: 2.5).', max_digits=4, verbose_name='Jours acquis par mois'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_starting_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Solde de départ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_starting_date',
            field=models.DateField(blank=True, help_text="Date à partir de laquelle s'applique le solde initial. Si vide, utilise la date de recrutement.", null=True, verbose_name='Date de départ du solde'),
        ),
        migrations.AddField(
            model_name='employee',
            name='min_working_days_for_accrual',
            field=models.PositiveSmallIntegerField(default=15, help_text='Nombre de jours de présence requis dans un mois pour obtenir le droit aux congés.', verbose_name='Jours minimum requis/mois'),
        ),
    ]
